FROM openjdk:15
ARG JAR_FILE
EXPOSE 8080

WORKDIR /opt/rukou

#dependencies
COPY target/dependency/accessors-smart-1.2.jar \
 target/dependency/activation-1.1.jar \
 target/dependency/adal4j-1.6.4.jar \
 target/dependency/adapter-rxjava-2.6.2.jar \
 target/dependency/animal-sniffer-annotations-1.17.jar \
 target/dependency/annotations-2.10.60.jar \
 target/dependency/annotations-4.1.1.4.jar \
 target/dependency/apache-client-2.10.60.jar \
 target/dependency/api-common-1.8.1.jar \
 target/dependency/asm-5.0.4.jar \
 target/dependency/async-http-client-2.10.4.jar \
 target/dependency/async-http-client-netty-utils-2.10.4.jar \
 target/dependency/auth-2.10.60.jar \
 target/dependency/auto-value-annotations-1.6.6.jar \
 target/dependency/aws-core-2.10.60.jar \
 target/dependency/aws-query-protocol-2.10.60.jar \
 target/dependency/azure-annotations-1.10.0.jar \
 target/dependency/azure-client-authentication-1.7.0.jar \
 target/dependency/azure-client-runtime-1.7.0.jar \
 target/dependency/azure-servicebus-3.1.4.jar \
 target/dependency/checker-compat-qual-2.5.5.jar \
 target/dependency/client-runtime-1.7.0.jar \
 target/dependency/commons-codec-1.11.jar \
 target/dependency/commons-lang3-3.5.jar \
 target/dependency/commons-logging-1.2.jar \
 target/dependency/converter-jackson-2.5.0.jar \
 target/dependency/error_prone_annotations-2.3.2.jar \
 target/dependency/eventstream-1.0.1.jar \
 target/dependency/failureaccess-1.0.1.jar \
 target/dependency/gax-1.48.1.jar \
 target/dependency/gax-grpc-1.48.1.jar \
 target/dependency/google-auth-library-credentials-0.17.1.jar \
 target/dependency/google-auth-library-oauth2-http-0.17.1.jar \
 target/dependency/google-cloud-core-1.90.0.jar \
 target/dependency/google-cloud-core-grpc-1.90.0.jar \
 target/dependency/google-cloud-pubsub-1.90.0.jar \
 target/dependency/google-http-client-1.31.0.jar \
 target/dependency/google-http-client-jackson2-1.31.0.jar \
 target/dependency/grpc-alts-1.23.0.jar \
 target/dependency/grpc-api-1.23.0.jar \
 target/dependency/grpc-auth-1.23.0.jar \
 target/dependency/grpc-context-1.23.0.jar \
 target/dependency/grpc-core-1.23.0.jar \
 target/dependency/grpc-google-cloud-pubsub-v1-1.72.0.jar \
 target/dependency/grpc-grpclb-1.23.0.jar \
 target/dependency/grpc-netty-shaded-1.23.0.jar \
 target/dependency/grpc-protobuf-1.23.0.jar \
 target/dependency/grpc-protobuf-lite-1.23.0.jar \
 target/dependency/grpc-stub-1.23.0.jar \
 target/dependency/gson-2.8.0.jar \
 target/dependency/guava-28.0-android.jar \
 target/dependency/http-client-spi-2.10.60.jar \
 target/dependency/httpclient-4.5.9.jar \
 target/dependency/httpcore-4.4.11.jar \
 target/dependency/j2objc-annotations-1.3.jar \
 target/dependency/jackson-annotations-2.9.0.jar \
 target/dependency/jackson-core-2.10.0.jar \
 target/dependency/jackson-databind-2.10.0.jar \
 target/dependency/jackson-datatype-joda-2.10.0.jar \
 target/dependency/javax.activation-1.2.0.jar \
 target/dependency/javax.annotation-api-1.3.2.jar \
 target/dependency/javax.mail-1.6.1.jar \
 target/dependency/jcip-annotations-1.0-1.jar \
 target/dependency/joda-time-2.9.9.jar \
 target/dependency/json-smart-2.3.jar \
 target/dependency/jsr305-3.0.2.jar \
 target/dependency/lang-tag-1.5.jar \
 target/dependency/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar \
 target/dependency/logging-interceptor-3.12.2.jar \
 target/dependency/netty-buffer-4.1.42.Final.jar \
 target/dependency/netty-codec-4.1.42.Final.jar \
 target/dependency/netty-codec-dns-4.1.42.Final.jar \
 target/dependency/netty-codec-http2-4.1.42.Final.jar \
 target/dependency/netty-codec-http-4.1.42.Final.jar \
 target/dependency/netty-codec-socks-4.1.42.Final.jar \
 target/dependency/netty-common-4.1.42.Final.jar \
 target/dependency/netty-handler-4.1.42.Final.jar \
 target/dependency/netty-handler-proxy-4.1.42.Final.jar \
 target/dependency/netty-nio-client-2.10.60.jar \
 target/dependency/netty-reactive-streams-2.0.3.jar \
 target/dependency/netty-reactive-streams-http-2.0.4.jar \
 target/dependency/netty-resolver-4.1.42.Final.jar \
 target/dependency/netty-resolver-dns-4.1.42.Final.jar \
 target/dependency/netty-transport-4.1.42.Final.jar \
 target/dependency/netty-transport-native-epoll-4.1.42.Final-linux-x86_64.jar \
 target/dependency/netty-transport-native-kqueue-4.1.42.Final-osx-x86_64.jar \
 target/dependency/netty-transport-native-unix-common-4.1.42.Final.jar \
 target/dependency/nimbus-jose-jwt-8.17.jar \
 target/dependency/oauth2-oidc-sdk-6.5.jar \
 target/dependency/okhttp-3.12.6.jar \
 target/dependency/okhttp-urlconnection-3.12.2.jar \
 target/dependency/okio-1.15.0.jar \
 target/dependency/opencensus-api-0.23.0.jar \
 target/dependency/opencensus-contrib-grpc-metrics-0.21.0.jar \
 target/dependency/opencensus-contrib-http-util-0.21.0.jar \
 target/dependency/perfmark-api-0.17.0.jar \
 target/dependency/profiles-2.10.60.jar \
 target/dependency/proto-google-cloud-pubsub-v1-1.72.0.jar \
 target/dependency/proto-google-common-protos-1.16.0.jar \
 target/dependency/proto-google-iam-v1-0.12.0.jar \
 target/dependency/protobuf-java-3.9.1.jar \
 target/dependency/protobuf-java-util-3.9.1.jar \
 target/dependency/protocol-core-2.10.60.jar \
 target/dependency/proton-j-0.33.2.jar \
 target/dependency/qpid-proton-j-extensions-1.2.2.jar \
 target/dependency/reactive-streams-1.0.2.jar \
 target/dependency/regions-2.10.60.jar \
 target/dependency/retrofit-2.5.0.jar \
 target/dependency/rxjava-1.3.8.jar \
 target/dependency/sdk-core-2.10.60.jar \
 target/dependency/slf4j-api-1.7.28.jar \
 target/dependency/slf4j-simple-1.7.28.jar \
 target/dependency/snakeyaml-1.26.jar \
 target/dependency/sqs-2.10.60.jar \
 target/dependency/threetenbp-1.3.3.jar \
 target/dependency/utils-2.10.60.jar ./

#actual code
COPY ${JAR_FILE} rukou-local.jar

CMD java -cp "*" io.rukou.local.Main